image: debian/stable
packages:
  - build-essential
  - autoconf
  - libtool
sources:
  - https://hg.sr.ht/~m6kvm/libhoratio
environment:
  deploy: palmer@overchat.org
tasks:
  - setup: |
      cd libhoratio
      hg clone -r dlscripts-0.4.0 https://hg.sr.ht/~m6kvm/dlscripts
      sudo apt-get install -q -y `dlscripts/build-deps.sh debian/control`
  - build: |
      cd libhoratio
      debian/rules
      make && make check
