#!/bin/bash

set -e

scriptdir=`dirname $0`;

# Is Mercurial available to the user?
which hg > /dev/null

# Do you have an Hg checkout of the project?
if [ -d "$scriptdir/../.hg" ]; then
	exit 0;
fi

exit 1;
